import Head from "next/head";
import { Navbar } from "@/organisms/Navbar/Navbar";
import { Header } from "@/organisms/Header/Header";
import { CtaDownload } from "@/organisms/CtaDownload/CtaDownload";
import { PersonalSummary } from "@/organisms/PersonalSummary/PersonalSummary";
import { Contact } from "@/organisms/Contact/Contact";

export default function Home() {
  return (
    <>
      <Head>
        <title>Website - Muhammad Raihan Satrio Putra Pamungkas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-neutral-900">
        <Navbar/>
        <Header/>
        <CtaDownload/>
        <PersonalSummary/>
        <Contact/>
      </main>
    </>
  );
}
