import Head from "next/head";

import { Text } from "@/atoms/Text/Text";
import { Navbar } from "@/organisms/Navbar/Navbar";
import { Button } from "@/atoms/Button/Button";
import { Bs0Circle } from "react-icons/bs";

export default function Home() {
  return (
    <>
      <Head>
        <title>Website - Muhammad Raihan Satrio Putra Pamungkas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar/>

        <h1 className="text-3xl font-barlow font-bold underline text-blue-900">Hello World !</h1>

        <button
          data-tooltip-target="tooltip-default"
          type="button"
          className="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
        >
          Default tooltip
        </button>
        <div
          id="tooltip-default"
          role="tooltip"
          className="absolute z-10 invisible inline-block px-3 py-2 text-sm font-medium text-white transition-opacity duration-300 bg-gray-900 rounded-lg shadow-sm opacity-0 tooltip dark:bg-gray-700"
        >
          Tooltip content
          <div className="tooltip-arrow" data-popper-arrow></div>
        </div>
        <div
          className="flex p-4 mb-4 text-sm text-blue-800 rounded-lg bg-blue-50 dark:bg-gray-800 dark:text-blue-400"
          role="alert"
        >
          <svg
            aria-hidden="true"
            className="flex-shrink-0 inline w-5 h-5 mr-3"
            fill="currentColor"
            viewBox="0 0 20 20"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              fillRule="evenodd"
              d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z"
              clipRule="evenodd"
            ></path>
          </svg>
          <span className="sr-only">Info</span>
          <div>
            <span className="font-medium">Info alert!</span> Change a few things up and try submitting again.
          </div>
        </div>
        <Text fontColor="red-900">TEST</Text>
        <div className="w-1/6">
          <Button
            icon={<Bs0Circle/>} 
            styleColor="primary"
            size="normal"
          >
            {"Want to Reach me ?"}
          </Button>
        </div>
      </main>
    </>
  );
}
